global:
  scrape_interval: 15s  # How often to scrape targets
  evaluation_interval: 15s  # How often to evaluate rules

scrape_configs:
  - job_name: "node_exporter"
    static_configs:
      - targets: ["15.206.117.207:9100"]  # Change to your node_exporter host and port

  - job_name: "blackbox_exporter"
    metrics_path: /probe
    params:
      module: [http_2xx]  # Probes for HTTP status 200
    static_configs:
      - targets:
          - "git@github.com:siva1369/shall_scripts.git"  # Change to the actual endpoint you want to monitor
          - "http://15.206.117.207:8080"
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: "15.206.73.47:9115"  # Blackbox Exporter address
rule_files:  # Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
  - "alert_rules.yml"   # this is a file name crearted in prometheus
  # - "second_rules.yml"